### PR TITLE
Pass map instance to onDrag handler

### PR DESCRIPTION
**Pull request by bogomya**
Goal:
Add possibility to work with google map api in the onDrag handler.
+ documentation improving

### CODE REVIEW

**Comment by itsmichaeldiego** [comment]
@bogomya Could you explain how this improves and provide an example? Just for documentation, I totally understand what you are doing

**Comment by bogomya** [comment]
The idea was to get map bounds on drag event to load new markers. I could use onChange, but onChange is called also when zoom event is occurred, and also on initial load.

**Comment by itsmichaeldiego** [comment]
@bogomya Thank you so much! This would be helpful. Could you provide a live example of this working? I need to check its working before releasing it.

**Comment by itsmichaeldiego** [comment]
@bogomya Merged and deployed in version `1.1.0`, please try it and let me know

**Pull request merged**
