### PR TITLE
Use React 16 portal to render map overlay

### LINKED ISSUE #642: Context (new API) is not propagated to google-map-react children
When using the new context API, google-map-react `children` cannot consume the context because `GoogleMapMarkers` is rendered outside of the rest of the component tree. 

A similar issue was created for the previous context API: https://github.com/google-map-react/google-map-react/issues/64 and was resolved by using `unstable_renderSubtreeIntoContainer`.

However, deprecated `unstable_renderSubtreeIntoContainer` does not work for the new context API.  For the new context API to be propagated properly, `ReactDOM.createPortal` from react 16 needs to be used instead.

**Expected Behaviour**
It's expected that when wrapping the Google map component with a context provider, the children to the Google map component will be able to consume the context

**Current Behaviour**
Children of the Google map component cannot consume the context provided from higher up in the tree.

### PR DESCRIPTION
**Pull request by clayne11**
This allows the new context API to propagate context properly.

Fixes #642.

Note: This is a breaking change since it will no longer support React < 16 and should be released as a new major version.

### CODE REVIEW

**Comment by jooj123** [comment]
this effectively means this component no longer supports react 15 - is this wise? we still use this component in a react 15 code base - its not always that trivial to move to the latest react on a large codebase

**Comment by itsmichaeldiego** [comment]
@jooj123 I am wondering if we should catch when the user is using 16+ and apply this code when so.

**Comment by jooj123** [comment]
@itsmichaeldiego yeah some sort of fallback would be good 
maybe even a 3rd party one like: https://github.com/tajo/react-portal

**Comment by clayne11** [comment]
React 16 has been out for over a year at this point and upgrading really isn't that difficult IMO. I can understand that we don't want to making a breaking change like this for in minor version but we can't continue to support React < 16 indefinitely.

It seems reasonable to me, at this point, that we publish a new major version with this breaking change and that the current version continues to live on as is.

If you want the latest and greatest features of anything you have to upgrade versions and deal with the migration (which from React 15 - 16 really is not that much). If you're happy with React 15 then by all means you can keep using it but the community has to move forward. A year is a long time in the frontend JavaScript world.

**Comment by itsmichaeldiego** [comment]
@clayne11 We added this with backwards compatibility in #696, so this becomes obsolete, thanks.

**Pull request closed without merging**
