### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by maruf89**
Update readme to show how to add Google Map API Libraries.

### CODE REVIEW

**Comment by barakplasma** [comment]
I think this PR should wait for https://github.com/google-map-react/google-map-react/issues/673 to be fixed first, since adding any library along with the heatmap layer currently causes the other libraries not to be loaded.

**Comment by itsmichaeldiego** [comment]
@maruf89 Ideally we want to pass them on the libraries object instead of one by one like that. CC @barakplasma

**Comment by itsmichaeldiego** [comment]
@barakplasma Thoughts on my last comment?

**Comment by barakplasma** [comment]
> @barakplasma Thoughts on my last comment?

I don't have a strong opinion on which API is better, whether to have a list of boolean props for each library or one 'libraries' object with the same props. I am only mildly inclined to 'namespace' the props under the libraries object, since it does seem a bit more neatly organized than the alternative.

**Comment by itsmichaeldiego** [comment]
@barakplasma That's a good idea! Would you like to work on that? Or @maruf89 ?

**Comment by barakplasma** [comment]
@maruf89 would you like to work on this?
I won't be able to work on this any time soon.

**Comment by maruf89** [comment]
No, I'm not doing anything with computers or coding anymore for a long long
while

wt., 16.04.2019, 12:23 użytkownik Michael Salaverry <
notifications@github.com> napisał:

**Comment by itsmichaeldiego** [comment]
@barakplasma Let me know if you still interested on this othwerwise I will create an issue and ask for help

**Comment by barakplasma** [comment]
Just to clarify, we are talking about fixing #673, or are we talking about updating the readme? I think we should recommend one _"right"_ way to add libraries.

**Comment by itsmichaeldiego** [comment]
@barakplasma I am talking about recommending one "right" way to add libraries, which I think will be under `libraries: ['bar', 'foo']`. And keeping this way to pass libraries instead of two.

**Comment by barakplasma** [comment]
I agree with putting libraries to load in the library object.

**Comment by itsmichaeldiego** [comment]
@barakplasma If so I think we should remove the other way, so there is only one way and no collision

**Comment by itsmichaeldiego** [comment]
Seems that this was taken care by #921

**Comment by itsmichaeldiego** [comment]
@barakplasma @maruf89 Let me know if that works for you folks

**Pull request closed without merging**
