### PR TITLE
Take #2: Add shouldUnregisterMapOnUnmount prop to persist map object on unmount

### PR DESCRIPTION
**Pull request by KevinRamsunder**
See previous discussion here #722 (comment)

Pls cut the tag just with this change; will help isolate bugs and prevent rolling back changes that didn't have defects

thanks!

### CODE REVIEW

**Comment by KevinRamsunder** [comment]
looks like the ci is having issues

**Comment by KevinRamsunder** [comment]
hey @itsmichaeldiego when you get a chance, can you take a look at this PR please? Separately, the CI is failing, but it doesn't seem specific to this change - any insights there?

**Comment by SL-BennettYau** [comment]
@KevinRamsunder  i was wondering how you re-render the map from your cache?
After caching the ref&map, i lose my map marker as well as the drag/zoom functionality of the map

**Comment by KevinRamsunder** [comment]
@SL-BennettYau you'll have to keep references to any of the custom listeners/markers you added, and then on the next mount, re-apply them to the map.

**Comment by itsmichaeldiego** [comment]
@KevinRamsunder @SL-BennettYau Merged and released in 1.1.5, let me know if it works

**Pull request merged**
