### PR TITLE
Custom div style options

### LINKED ISSUE #632: Custom overlayview style attributes
Would be great if it would be possible to add custom style properties to div or panes.

https://github.com/google-map-react/google-map-react/blob/master/src/google_map.js#L589

In my case I need to add `pointer-events: none` (an overlapping issue with custom tiles and an interesting way of rendering stuff in general).

Could that be possible? I can get there trough refs, but i would prefer an API.

### PR DESCRIPTION
**Pull request by jurgenzz**
fixes #632

### CODE REVIEW

**Comment by jurgenzz** [comment]
Usage: 
```

**Comment by jurgenzz** [comment]
I'd guess no, as for name `wrapper` i would think of the `div` surrounding `<GoogleMapReact />` component itself, not just marker, which actually goes into a pane. A lot of other overlays there :) . Then we could think of `markerContainerStyle` and other, but by just having a quick look at source, you'd figure out that `this.div` is probably getting all the styles. But i can change to something else tomorrow :)

**Comment by itsmichaeldiego** [comment]
@jurgenzz Yes, I think we could find a more descriptive name for this, as this div can be any div.

**Comment by itsmichaeldiego** [comment]
@jurgenzz How are we looking on this? I would like to merge it and release it so we can close #632

**Comment by itsmichaeldiego** [comment]
@jurgenzz That is great! Thanks, I just realize something (sorry I didn't before) but we need to add this to the DOCS so other people know is there, more specifically in the [API.md file](https://github.com/google-map-react/google-map-react/blob/master/API.md)

**Comment by jurgenzz** [comment]
If you want, you can release it as it is for now. I've created reminder for Monday, when i'll be at work i'll update docs and API.md file.

**Comment by itsmichaeldiego** [comment]
@jurgenzz We can wait, thanks!

**Comment by jurgenzz** [comment]
Ye, sorry, updated now :)

**Comment by itsmichaeldiego** [comment]
@jurgenzz Great work man! I am releasing this in `1.0.9`!

**Comment by itsmichaeldiego** [comment]
@jurgenzz Released in 1.0.9!

**Pull request merged**
