### PR TITLE
Avoid null error

### PR DESCRIPTION
**Pull request by asundlihardig**
Avoid the error "Cannot read property 'removeEventListener' of null"

### CODE REVIEW

**Comment by itsmichaeldiego** [comment]
@asundlihardig Could you provide a screenshot showing the error ?

**Comment by asundlihardig** [comment]
I'm sorry @itsmichaeldiego . The error was reported through Sentry.io

**Comment by itsmichaeldiego** [comment]
@asundlihardig Sorry I can't merge this without you showing me how this is blocking you or where is the error. There are thousands of places in the code where we could add defensive programming, I need to know why adding it here would make the difference.

**Comment by itsmichaeldiego** [comment]
@asundlihardig Looking forward to hear back from you! Would like to merge this if its an issue for the users.

**Pull request merged**
