### PR TITLE
Clustering and Spiderify

### PR DESCRIPTION
**Pull request by mukulb90**
We use Google-map-react very heavily in our projects and like many others, we too ran into the problem of too many markers. Most obvious solution to solve it was Clustering and Spiderify. 

Clustering ->  Two or more markers join together to form a cluster .

Spiderify -> When two or more markers are at exactly same latLng, plotting a lot of markers gave a very bad UX. We had a use case where we had to plot more than 100 markers at exactly same latLng .

I read a solution where you have mentioned to use point-cluster to form clusters externally and pass clusters as normal markers to Google-Map-React . 

On the same lines, I have Implemented an HOC : GoogleMapReactWithClustering
Which enhances GoogleMapReact with clustering and spiderifying where we just need to pass React Components representing Cluster and Spiders and it will do the rest.
Also, one of the requirements for us was that clusters should split smoothly so that you can make sense of which marker came from which cluster on zooming in.

This is how it works for us :- http://jmp.sh/zeGtADw

I wasn't sure what directory structure to follow . So, i have put src code in develop/clustering for now .

### CODE REVIEW

**Comment by istarkov** [comment]
Super!
IMO it will be `10x` better if you provide this as your own standalone enhancer library and provide a Pull Request with link to your library in current Readme.

**Comment by Tim152** [comment]
@istarkov hi! I was create a simple example without recompose, based on your [desicion](https://github.com/istarkov/google-map-clustering-example) 
https://github.com/Tim152/clustering-google-map-react

**Comment by itsmichaeldiego** [comment]
@Tim152 Feel free to do what @istarkov said before and add the enhacer to our Readme

**Comment by itsmichaeldiego** [comment]
@mukulb90 You still active?

**Comment by mukulb90** [comment]
Yes michael

**Comment by itsmichaeldiego** [comment]
@mukulb90 I would like to work with you to see if we can add this feature

**Comment by mukulb90** [comment]
Sure, What do you have in mind ?

**Comment by itsmichaeldiego** [comment]
@mukulb90 Well, first, we would have to fix the conflicts and then we can go two ways, we've a a organization now, so we can have a "standalone enhancer library" as @istarkov pointed out, or we can discuss if we want to add clustering to this one. 

I would like to see both options but first I would need you to fix the conflicts so I can test it, and test the size of the build.

Would you mind fixing conflicts and updating to latest master?

Thanks! 🎉

**Comment by mukulb90** [comment]
@itsmichaeldiego I have fixed the conflicts here

**Comment by itsmichaeldiego** [comment]
@mukulb90 Did you check? I just did a find in page and found it https://github.com/google-map-react/google-map-react/pull/284/files#diff-e8b86504901df43bfb0218a9db49bb7bR95

**Comment by taylorjames** [comment]
hey @itsmichaeldiego what is the status of this? I would like to have clustering in my implementation.

**Comment by natcodes** [comment]
hello @itsmichaeldiego @mukulb90 what is the status of this? I would also like to use clustering.

**Comment by GodLesZ** [comment]
@mukulb90 @itsmichaeldiego why was this issue closed?
Any news on for that feature?

**Comment by itsmichaeldiego** [comment]
@taylorjames @GodLesZ @natcodes My ideal idea was to create another library because this changes might affect this one. But if anybody wants to create a PR similar to @mukulb90's, I am happy to help review and merge!

**Pull request closed without merging**
