### PR TITLE
Update API.md

### PR DESCRIPTION
**Pull request by vulong23**
Because the parent node of marker has size 0x0, top 50% and right 50% would affect nothing. You only need to translate(-50%, -50%) to move it to the right position.

### CODE REVIEW

**Comment by itsmichaeldiego** [comment]
@vulong23 Thanks for your contribution, you're right! 

The build is not passing as it was broken, its fixed now, would you mind rebasing with latest master?

**Comment by itsmichaeldiego** [comment]
@vulong23 Mm the rebase did not work as expected, you've changed 5 files.

**Comment by vulong23** [comment]
@itsmichaeldiego lol I messed up with git again, I'll create a new pull request

**Comment by itsmichaeldiego** [comment]
@vulong23 No worries!

**Pull request closed without merging**
