### PR TITLE
Add shouldUnregisterMapOnUnmount prop to persist map object on unmount

### PR DESCRIPTION
**Pull request by KevinRamsunder**
Each call to initialize a new map incurs an additional cost with Google's new billing platform.

In order to re-use the map instance between individual components, the following changes have been made:

1) Adds a `shouldUnregisterMapOnUnmount` prop to prevent the deletion of the map object, so it can be re-used.

2) Exposes the ref to the `googleMapDom_` via the `_onGoogleApiLoaded` callback, so it can be cached in a consuming application.

### CODE REVIEW

**Comment by KevinRamsunder** [comment]
Fixed tests. Attached a screenshot of this fix working in my app (unfortunately, I can't share more than this due to proprietary reasons). Each "recordevent" is equal to one billing event.

The image on the left was before this fix, and the image on the right is after the fix. Note, the caching of the map/ref objects must be done in the consuming application -- this PR simply exposes the ref to facilitate that process.

screen shot 2019-02-18 at 6 58 40 pm

**Comment by itsmichaeldiego** [comment]
@KevinRamsunder This is looking good! And will decrease the billing of the users, thanks for the change! I am deploying it soon

**Comment by KevinRamsunder** [comment]
@itsmichaeldiego thanks! any idea when this might be tagged for release?

**Comment by itsmichaeldiego** [comment]
@KevinRamsunder Published in v 1.1.3

Let me know if everything is working as expected, thanks.

**Comment by itsmichaeldiego** [comment]
@KevinRamsunder This PR caused 
- https://github.com/google-map-react/google-map-react/issues/736
- https://github.com/google-map-react/google-map-react/issues/737 
Can you take a look?

**Comment by itsmichaeldiego** [comment]
@KevinRamsunder Reverting for now, cannot afford to have a broken version, please open a new PR that works properly! Thanks in advance

**Comment by KevinRamsunder** [comment]
@itsmichaeldiego the issues you mentioned don't appear to be related to my change - it was simply a prop change which is coded with backwards compatibility in mind. No functionality changes if the user doesn't opt in. The issues you pointed out are likely related to https://github.com/google-map-react/google-map-react/pull/726, which explicitly states that it ` handles bootstrapURLKeys change and reloads the Google Maps API`

With that being said, I do understand why you reverted this - but hope we can get it back in the future. Thanks!

**Comment by itsmichaeldiego** [comment]
@KevinRamsunder Lets create another PR and I will merge it!

**Comment by goncharov** [comment]
Hi, @KevinRamsunder, @itsmichaeldiego. Can you please provide example of usage of this option? I don't get how to reuse map object between google-map-react component instances

**Comment by RithikaChowta** [comment]
@KevinRamsunder @itsmichaeldiego Any update on the above query?

**Comment by managervcf** [comment]
@KevinRamsunder Providing `shouldUnregisterMapOnUnmount={false}` doesn't unregister the map instance, therefore reduces number of map intances created by [Maps JavaScript API](https://developers.google.com/maps/documentation/javascript), is that correct? 


I'm looking to minimze the costs of Maps JavaScript API by reducing number of map loads - [Price per MAP LOAD](https://developers.google.com/maps/billing-and-pricing/pricing#dynamic-maps).

**Pull request merged**
